version: '3.8'

services:
  mis-ticketing-v1:
    build:
      context: .
      dockerfile: Dockerfile
    container_name: mis-ticketing-v1
    ports:
      - "9009:9009"
    environment:
      NODE_ENV: production
      NEXT_TELEMETRY_DISABLED: 1
    restart: unless-stopped
