version: '3.8'

services:
  mis-ticketing-v1:
    build: .
    ports:
      - "9009:9009"
    environment:
      - NODE_ENV=production
    restart: unless-stopped
    networks:
      - barn-network

networks:
  ticketingv1-network:
    driver: bridge